#----------------------------------------------------------------------
# GCTA power calculator - for genetic correlation
## between a behavioural trait/ brain measure
## given h2 estimates and N
## used for LDSC genetic correlation analysis, which may be not super precise...
#----------------------------------------------------------------------
library(tidyr); library(dplyr)
rm(list=ls())
#----------------------------------------------------------------------

#----------------------------------------------------------------------
options(stringsAsFactors = FALSE)
# define pattern for this run
root="UKB_BIG40"

# define working_dir
if (Sys.info()['sysname']=='Windows') {dir="F:/projects/"} else {dir="/export/home/acarrion/acarrion/projects/"}
public_gwas_dir=paste(dir,"resources/datasets/GWAS_sumstats/ldsc/",sep="")
out_dir=paste(public_gwas_dir,"UKB_BIG40/cerebellum/",sep="")
# Get functions from:
## https://gcta.freeforums.net/thread/164/gcta-greml-power-calculator
scripts_dir=paste0(dir,"/resources/datasets/ABCD/scripts/genetics/ldsc/")
source(paste0(scripts_dir,"GCTA_PowerCalculator.R"))

setwd(out_dir)

#----------------------------------------------------------------------
## read estimates from Public GWASes
estimates_beh<-read.csv(paste(public_gwas_dir,"ldsc_h2_publicGWASes.csv",sep=""),header=TRUE)
estimates_beh<-estimates_beh %>% filter(Trait_name=="IQ"|
                                          Trait_name=="CP"|
                                          Trait_name=="EA3"|
                                          Trait_name=="LeftHandedness"|
                                          Trait_name=="DDyslexia")

# read estimates from heritability analyses, min and max for phenotypes of interest
## generated by: hsq_results_parse.R
estimates_brain<-read.csv(paste(out_dir,"ldsc_h2_",root,"_cerebellum.csv",sep=""),header=TRUE)
#----------------------------------

#----------------------------------
# Define variables, h2 and rg - for all models
rgs=unique(c(seq(0.01,0.30,0.001),seq(0.31,0.49,0.01),seq(0.5,1,0.05))) #60

#----------------------------------
# Trait 1 QT
#----------------------------------
estimates_qt<-estimates_beh%>% filter(Trait=="Quant")
resultsQT <- data.frame(trait1=as.character(),trait2=as.character(),
                        N_1 = as.numeric(), N_2=as.numeric(),
                        h2_1 = as.numeric(), h2_2= as.numeric(), 
                        rg= as.numeric(), 
                        se = as.numeric(), ncp = as.numeric(), pwr = as.numeric())

# for each of the cognitive traits, run power analysis
## Quantiative traits
for (j in 1:NROW(estimates_qt)){
  h1<-estimates_qt$estimate[j]
  p1<-estimates_qt$Trait_name[j]
  n1<-estimates_qt$N[j]
  for (i in 1:NROW(estimates_brain)){
  
  h2<-estimates_brain$h2[i]
  n2<-estimates_brain$N[i]
  p2<-estimates_brain$IDP_short_name[i]
    if (!is.na(h2)){
      for (rg in rgs){
          tmp <- calcBiQt(n1=n1, n2=n2,hsq1 =h1,hsq2=h2,rg=rg,overlap=FALSE)
          resultsQT[nrow(resultsQT)+1,] <- c(list(trait1=p1,trait2=p2,N_1=n1,N_2=n2,hsq1=h1,hsq2=h2,rg=rg),tmp)
      }
    rm(rg,tmp,h2,n2,p2)
    
  }
  rm(h2)
  }
}

resultsQT$rg<-as.numeric(resultsQT$rg)

#----------------------------------
# Trait 1 binary
#----------------------------------
estimates_bin<-estimates_beh %>% filter(Trait=="Binary")

resultsCC <- data.frame(trait1=as.character(),trait2=as.character(),
                        N_2 = as.numeric(), N_1cases=as.numeric(), N_1controls=as.numeric(),
                        case_prev=as.numeric(),h2_1 = as.numeric(), h2_2= as.numeric(), rg= as.numeric(),
                        se = as.numeric(), ncp = as.numeric(), pwr = as.numeric())

# for each of the binary traits, run power analysis
## Binary traits
for (j in 1:NROW(estimates_bin)){
  h1<-estimates_bin$estimate[j]
  p1<-estimates_bin$Trait_name[j]
  n1_cases<-estimates_bin$Ncases[j]
  n1_controls<-estimates_bin$Ncontrols[j]
  k<-estimates_bin$PopPrevalence[j]
  for (i in 1:NROW(estimates_brain)){
    
    h2<-estimates_brain$h2[i]
    n2<-estimates_brain$N[i]
    p2<-estimates_brain$IDP_short_name[i]
    if (!is.na(h2)){
      for (rg in rgs){
        
        tmp<-calcBiQtCc(n=n2,ncase=n1_cases,ncontrol=n1_controls,hsq1 =h1,hsq2=h2,rg=rg,K=k)
        resultsCC[nrow(resultsCC)+1,] <- c(list(trait1=p1,trait2=p2,
                                                N_2=n1,
                                                N_1cases=n1_cases,N_1controls=n1_controls,case_prev=k,
                                                hsq1=h1,hsq2=h2,
                                                rg=rg),tmp)
      }
      rm(rg,tmp)
    }
    rm(h2,n2,p2)

  }
  rm(h1,p1,n1_cases,n1_controls,k)
}


# combine resultsQT and resultsCC
resultsQT$Trait1Type<-"QT"
resultsCC$Trait1Type<-"Binary"

results<-merge(resultsQT,resultsCC,all=TRUE)
results<-merge(results,estimates_brain %>% select(IDP_short_name,parcellation,measure,lobe,region,hemisphere),by.x="trait2",by.y="IDP_short_name",all=TRUE)
trait1<-estimates_beh %>% select(Trait_name,ref,Reported.trait)
trait1<-trait1[!duplicated(trait1),]
results<-merge(results,trait1,by.x="trait1",by.y="Trait_name")
# save files
write.csv(results,paste(out_dir,"power_calc_results_",root,".csv",sep=""),row.names = FALSE)
