#!/bin/bash
#$ -N lava_pcor
#$ -o /export/home/acarrion/acarrion/projects/general_scripts/genotyping/lava/sge/
#$ -e /export/home/acarrion/acarrion/projects/general_scripts/genotyping/lava/sge/
#$ -cwd
#$ -q short.q
#$ -S /bin/bash
#$ -M acarrion@bcbl.eu
#$ -m as

#export OMP_NUM_THREADS=1 # n/o threads per process (important for parallelisation)


### This job script which will copy all the data to the temp dir, perform the analysis for a single phenotype pair, and copy the results back
#----------------------------------------------------------------------
# parameters passed from the submission script
source $1 # path for settings file
P1=$2 # phenotype 1
P2=$3 # phenotype 2
P3=$4 # phenotype to condition on
#----------------------------------------------------------------------
# copy data to tempdir
#----------------------------------------------------------------------
##cp $DATA/$P1.sumstats.txt $DATA/$P2.sumstats.txt $TMPDIR	# sumstats
##cp $DATA/$INFOFILE $DATA/$OVERLAP $DATA/$LOCFILE $TMPDIR	# info file / sample overlap / locus file
##cp $REFDIR/$REFDAT* $TMPDIR					# reference data
##cp lava_rg.R $TMPDIR						# analysis script
##cd $TMPDIR
#
## sumstats: get path to sumstats file -> copy to tmpdir
find ${sumstats_dir} -name ${P1}.sumstats.gz | xargs cp -t ${TMPDIR} # sumstats p1
find ${sumstats_dir} -name ${P2}.sumstats.gz | xargs cp -t ${TMPDIR} # sumstats p2
find ${sumstats_dir} -name ${P3}.sumstats.gz | xargs cp -t ${TMPDIR} # sumstats p2
# copy over if not already present - to avoid clashes across runs?

# info file / sample overlap / locus file
if [ ! -f ${TMPDIR}/${info_file} ]; then cp ${working_dir}/${info_file} ${TMPDIR}; fi # info file
if [ ! -f ${TMPDIR}/${overlap_file} ]; then cp ${working_dir}/${overlap_file} ${TMPDIR}; fi # sample overlap
if [ ! -f ${TMPDIR}/${info_file} ]; then cp ${working_dir}/${overlap_file} ${TMPDIR}; fi # locus file
#
if [ ! -f ${TMPDIR}/${overlap_file} ]; then cp ${ref_dir}/${ref_dat}* ${TMPDIR}; fi # reference data
cp ${scripts_dir}/lava_pcor.R ${TMPDIR} # analysis script
#----------------------------------------------------------------------
## ANALYSE ## 
cd ${TMPDIR}
# check that univ results are available for both phenotypes
if [ -f ${out_dir}/${P1}.univ ] && [ -f ${out_dir}/${P2}.univ ] && [ -f ${out_dir}/${P3}.univ ]; then
 if [ -f ${out_dir}/${P1}.${P2}.bivar ]; then
    # copy univ results for the phenotypes to tmpdir / if not already there
    if [ ! -f ${TMPDIR}/${P1}.univ ]; then cp ${out_dir}/${P1}.univ ${TMPDIR}; fi
    if [ ! -f ${TMPDIR}/${P2}.univ ]; then cp ${out_dir}/${P2}.univ ${TMPDIR}; fi
    if [ ! -f ${TMPDIR}/${P3}.univ ]; then cp ${out_dir}/${P3}.univ ${TMPDIR}; fi
    if [ ! -f ${TMPDIR}/${P1}.${P2}.bivar ]; then cp ${out_dir}/${P1}.${P2}.bivar ${TMPDIR}; fi
    # run local partial rg
    Rscript lava_pcor.R ${ref_dat} ${loc_file} ${info_file} ${overlap_file} "${P1};${P2}" "${P3}" "${P1}.${P2}_condBy.${P3}"
    # copy results to local output dir (as specified in settings.sh) 
    mv ${P1}.${P2}_condBy.$P3.* ${out_dir}
 else
   echo "Univariate or bivariate output files are not available for " ${P1} ${P2} ${P3}", please run lava_univ_sge.job first."
fi
fi

#----------------------------------------------------------------------