#!/bin/bash
#$ -N lava_univ
#$ -o /export/home/acarrion/acarrion/projects/general_scripts/genotyping/lava/sge/
#$ -e /export/home/acarrion/acarrion/projects/general_scripts/genotyping/lava/sge/
#$ -cwd
#$ -q long.q
#$ -S /bin/bash
#$ -M acarrion@bcbl.eu
#$ -m as

#export OMP_NUM_THREADS=1 # n/o threads per process (important for parallelisation)


### This job script which will copy all the data to the temp dir, perform the analysis for a single phenotype pair, and copy the results back
#----------------------------------------------------------------------
# parameters passed from the submission script
source $1 # path for settings file
P1=$2 # phenotype 1
#----------------------------------------------------------------------
# copy data to tempdir
#----------------------------------------------------------------------
##cp $DATA/$P1.sumstats.txt $DATA/$P2.sumstats.txt $TMPDIR	# sumstats
##cp $DATA/$INFOFILE $DATA/$OVERLAP $DATA/$LOCFILE $TMPDIR	# info file / sample overlap / locus file
##cp $REFDIR/$REFDAT* $TMPDIR					# reference data
##cp lava_rg.R $TMPDIR						# analysis script
##cd $TMPDIR
#
## sumstats: get path to sumstats file -> copy to tmpdir
# find ${sumstats_dir} -name ${P1}.sumstats.gz | xargs cp -t ${TMPDIR} # sumstats p1

# copy over if not already present - to avoid clashes across runs?

# info file / sample overlap / locus file
if [ ! -f ${TMPDIR}/${info_file} ]; then cp ${working_dir}/${info_file} ${TMPDIR}; fi # info file
if [ ! -f ${TMPDIR}/${overlap_file} ]; then cp ${working_dir}/${overlap_file} ${TMPDIR}; fi # sample overlap
if [ ! -f ${TMPDIR}/${info_file} ]; then cp ${working_dir}/${overlap_file} ${TMPDIR}; fi # locus file
#
if [ ! -f ${TMPDIR}/${overlap_file} ]; then cp ${ref_dir}/${ref_dat}* ${TMPDIR}; fi # reference data
cp ${scripts_dir}/lava_univ.R ${TMPDIR} # analysis script
#----------------------------------------------------------------------
## ANALYSE ## 
cd ${TMPDIR}
Rscript lava_univ.R ${ref_dat} ${loc_file} ${info_file} ${overlap_file} "$P1" "$P1"
#----------------------------------------------------------------------
# copy results to local output dir (as specified in settings.sh) 
mv ${P1}.univ ${out_dir}
#----------------------------------------------------------------------